language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - gfortran
      - libatlas-base-dev
install:
  - travis_retry pip install --upgrade pip wheel
  - travis_retry pip install numpy
  - travis_retry pip install unittest2
  - travis_retry pip install h5py
  - travis_wait 30 pip install scipy
  - if [ ! "$(ls -A tests/data)" ]; then wget https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20160519.tar.gz -O xu_testdata.tar.gz && tar xzf xu_testdata.tar.gz -C tests; fi
cache:
  pip: true
  directories:
   - tests/data
# command to run tests
script: python setup.py test
