language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly"
# command to install dependencies
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - gfortran
      - libatlas-base-dev
install:
  - pip install unittest2
  - pip install h5py
  - travis_wait 30 pip install scipy
  - wget https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20160519.tar.gz -O xu_testdata.tar.gz
  - tar xzf xu_testdata.tar.gz -C tests
cache: pip
# command to run tests
script: python setup.py test
