name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: master

jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: 'tox tox-wheel'
    jobs:
      py38:
        before:
          - task: Cache@2
            inputs:
              key: testdata20190812
              path: $(System.DefaultWorkingDirectory)/tests/data
              cacheHitVar: TESTDATA_RESTORED
            displayName: Cache test data
          - script: |
              curl -s -L https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20190812.tar.gz -o xu_testdata.tar.gz
              tar xzf xu_testdata.tar.gz -C tests
            condition: ne(variables.TESTDATA_RESTORED, 'true')
            displayName: Download test data
        after:
          - publish: $(System.DefaultWorkingDirectory)/dist/
            artifact: Python Wheel package
        image: [linux]
      py37:
        image: [linux, windows, macOs]
    coverage:
      with_toxenv: 'coverage'
      for_envs: [py37, py38]
