name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: master

jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: 'tox tox-wheel'
    jobs:
      py38:
        before:
          -script: |
            if [ ! "$(ls -A tests/data)" ]; then
              curl -s -L https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20190812.tar.gz -o xu_testdata.tar.gz
              tar xzf xu_testdata.tar.gz -C tests
            fi
        image: [linux]
        after:
          - task: Cache@2
            inputs:
              key: testdata20190812
              path: $(System.DefaultWorkingDirectory)/tests/data
            displayName: Cache test data
      py37:
        image: [linux, windows, macOs]
    coverage:
      with_toxenv: 'coverage'
      for_envs: [py37, py38]
